### PR TITLE
TLS / SSL Support

### LINKED ISSUE #8: Add support for TLS client certificates

### PR DESCRIPTION
**Pull request by fenos**
This PR Introduce Client TLS / SSL support as well as Mutual SSL support. 
fixes #8 #21 

### UI Preview

**Un-secure connection:**
screenshot 2018-12-24 at 01 39 22

**TLS / SSL Manager**
screenshot 2018-12-24 at 01 42 08

**Secured Connection**
screenshot 2018-12-24 at 01 44 54

### CODE REVIEW

**Comment by tmegow** [comment]
I really appreciate this addition, thank you!

**Comment by mprigge** [comment]
I wanted to echo all of what @tmegow said. This is a great feature, but it took a trip through the source to see how the files were supposed to be used. I did get it working - it just wasn't clear what was supposed to be where. 

For anyone else ending up here via a google search as I did, if you want to do mutual auth this is what goes in the options (as far as I can tell):

- **Root Certificate**: Should be a PEM-formatted file containing either the public key used on the gRPC service you're connecting to *or* the CA cert used to sign it (either seems to work).
- **Private Key**: Should be a PEM-formatted file containing the private key you want to use for client auth.
- **Cert Chain**: Should be a PEM-formatted file containing the public key you want to use for client auth (if this is signed by a CA, it doesn't appear to need to also contain the full chain as the name would suggest).
- **SSL Target Host**: Should be the CN on the public cert on the service you're connecting to. Does not need to be the actual fqdn BloomRPC is making the connection to, though. Just matters that it matches the CN of the cert which will answer (this lets you deal with a situation where you're port-forwarding and they don't match, for instance).

Anyway - great work @fenos.

**Comment by yunhan0** [comment]
Is there any support for mutual TLS? I've tried the steps above but it doesn't seem to work

**Comment by mprigge** [comment]
Without getting a bunch of potentially security-sensitive info from your service implementation from you, all I can say is that it does work for me given the guidelines above (please feel free to email me if you like, though!). 

It definitely is extremely difficult to see what's wrong when it doesn't work, though. The underlying transport is extremely opaque about what the problem actually is and Bloom RPC's odd UI surrounding this feature really doesn't help things. It took me several hours of experimentation to find the right combination of settings/files/formats to make everything work. 

However, I do regularly use this to run gRPC requests via a port-forwarded tunnel to services running in a kubernetes environment that use mutual TLS auth. So, it does work. It's just goofy.

**Comment by indera-shsp** [comment]
@mprigge Is there a log file created somewhere?

I was looking for a way to enable debug mode in the application but no luck

```
DEBUG_PROD=true /usr/bin/open -a /Applications/BloomRPC.app/
``` 



== Relevant code to TLS config 
**app/behaviour/sendRequest.ts**

```
  /**
   * Get grpc client for this relevant request
   * @param serviceClient
   */
  private getClient(serviceClient: any): grpc.Client {
    let creds = credentials.createInsecure();
    let options = {};

    if (this.tlsCertificate) {
      if (this.tlsCertificate.sslTargetHost) {
        options = {
          ...options,
          'grpc.ssl_target_name_override' : this.tlsCertificate.sslTargetHost,
          'grpc.default_authority': this.tlsCertificate.sslTargetHost,
        }
      }
      if(this.tlsCertificate.useServerCertificate === true) {
        creds = credentials.createSsl();
      } else {
        creds = credentials.createSsl(
            fs.readFileSync(this.tlsCertificate.rootCert.filePath),
            this.tlsCertificate.privateKey && fs.readFileSync(this.tlsCertificate.privateKey.filePath),
            this.tlsCertificate.certChain && fs.readFileSync(this.tlsCertificate.certChain.filePath),
        );
      }
    }

    return new serviceClient(this.url, creds, options);
  }
```

**Pull request merged**
