### PR TITLE
Fix parsed options

### PR DESCRIPTION
**Pull request by int3cd**
The package needs to be updated to resolve the bug https://github.com/uw-labs/bloomrpc/issues/389 and https://github.com/uw-labs/bloomrpc/issues/96

The problem comes from a parsing error. In the package protobufjs, the bug has already been fixed: https://github.com/protobufjs/protobuf.js/pull/1256

### CODE REVIEW

**Comment by george-angel** [comment]
@int3cd I don't manage this project (or ever touched NodeJS in my life), the initial author of the project has left the company.

I'm trying to figure out the fate of the project internally, please bare with, I will post an update later today.

**Review by daylerees — APPROVED** [review]
Built using this branch and tested. Seems to work fine. No obvious regressions. 👍 Thanks!

**Comment by int3cd** [comment]
@george-angel @daylerees 

Will we merge request and release a new release this week?

**Comment by george-angel** [comment]
@int3cd Sorry - would you mind resolving?

I will merge and have a look at creating a release.

Thanks!

**Comment by int3cd** [comment]
@george-angel , can you make a new release 1.5.4?

**Comment by george-angel** [comment]
Hey @int3cd - please see - https://github.com/bloomrpc/bloomrpc/issues/398

Utility Warehouse has decided to release the project into public domain and we are looking for maintainers to look after the project.

I'm only around to hand over the reigns, so please reach out to one of the volunteers - thanks!

**Pull request merged**
