### PR TITLE
grpc-web support

### LINKED ISSUE #72: grpc-web support
Would love to see this gets prioritised.

Do you accept contribute on this matter? We love this tool, but when it comes to grpc-web, we can't find anything easy to use.

### PR DESCRIPTION
**Pull request by jackielii**
fixes #72

### CODE REVIEW

**Comment by fenos** [comment]
I will try to get his merged over the weekend

**Comment by jackielii** [comment]
> I will try to get his merged over the weekend

Cool, thanks.

If you don't mind, could you review the merged PR #218 which includes both the keyboard shortcut fix as well as grpc-web support.

We have been using this for a few days now:

image

**Comment by EraYaN** [comment]
Having this merged would be very useful

**Comment by nateshmbhat** [comment]
any updates on this ? @fenos

**Comment by gary-lo** [comment]
Any ideas why this isn't merged?

**Comment by jackielii** [comment]
moved to #218

**Pull request closed without merging**
